### PR TITLE
Update docs for version to 2.0.0

### PR DESCRIPTION
**Pull request by jeffboutotte**

### CODE REVIEW

**Comment by jeffboutotte** [comment]
@pfn how do you feel about publishing a version 2.0.0 of this plugin for sbt 1.x?  I have the snapshot version published to an internal artifactory for our company, but would prefer to use an actual published version if possible.

**Comment by pfn** [comment]
@jeffboutotte I'll see what I can do about publishing a 2.0.0 for you, let me take in all the PRs and see.

**Comment by jeffboutotte** [comment]
@pfn awesome - thank you! Let me know if there are any outstanding issues you have concerns about before releasing a version 2.0.0, I'm happy to dig in and contribute fixes.

**Comment by pfn** [comment]
I'll merge this and try to get this published over the weekend or Monday. Thanks for your help!

**Comment by jeffboutotte** [comment]
Awesome - thank you!

**Comment by pfn** [comment]
Thanks for your help!

**Pull request merged**
