### PR TITLE
Remove brittle argument parsing reflection

### PR DESCRIPTION
**Pull request by Sineaggi**
Not sure if this is how you want to fix newer kotline versions, but here's a quick hack getting it to work.
FYI [this](https://github.com/JetBrains/kotlin/commit/78c0111c6e85b54a2ba4ddd766099dabb4d633bd) commit removes the Args class in favor of a built in argument parser. We could try to look for that class but I think that's headed down the wrong path.

### CODE REVIEW

**Comment by pfn** [comment]
I appreciate the PR. Some questions:

* How backward compatible is this change?
* Does it require a min kotlin version?

If the answer to either is "not very compatible, or requires a very new/EAP version" -- I would prefer to keep the existing Args lookup, and fallback to this workaround/use-of-internal Args parser when the method is present.

Thanks!

**Comment by Sineaggi** [comment]
I should have mentioned in my PR but...
- It works with the currently set kotlin version and future versions
- It shouldn't require a min kotlin version

Though I guess I'm not sure what the argument parsing was doing in the first place.

**Comment by pfn** [comment]
The use of `Args` predated kotlin switching to do it internally. But if you say this works on the current default version set (1.1.2)--good enough for me. Thanks

**Comment by pfn** [comment]
Coming back to this PR, it breaks all argument parsing altogether... odd, I thought I had travis hooked up to this project...

**Comment by Sineaggi** [comment]
Oh wow, thanks for coming back to this. I didn't notice during testing.

**Pull request merged**
